const points = [
    { name: "A", value: 1 },
    { name: "B", value: 3 },
    { name: "C", value: 3 },
    { name: "D", value: 2 },
    { name: "E", value: 1 },
    { name: "F", value: 4 },
    { name: "G", value: 2 },
    { name: "H", value: 4 },
    { name: "I", value: 1 },
    { name: "J", value: 8 },
    { name: "K", value: 5 },
    { name: "L", value: 1 },
    { name: "M", value: 3 },
    { name: "N", value: 1 },
    { name: "O", value: 1 },
    { name: "P", value: 3 },
    { name: "Q", value: 10 },
    { name: "R", value: 1 },
    { name: "S", value: 1 },
    { name: "T", value: 1 },
    { name: "U", value: 1 },
    { name: "V", value: 4 },
    { name: "W", value: 4 },
    { name: "X", value: 8 },
    { name: "Y", value: 4 },
    { name: "Z", value: 10 },
    { name: '\xa0\xa0', value: 0}
]

export default points;